<template>
<div>
    <div class="tickets slide-right">
        what
    </div>
</div>
</template>
<script>
export default {
    data(){
        return {
            array:[1,2,3,4,5,6,7,8]
        }
    }
}
</script>
<style lang="scss">
/* ----------------------------------------------
 * Generated by Animista on 2018-11-21 12:4:21
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-right
 * ----------------------------------------
 */
/* @-webkit-keyframes slide-right {
  0% {
    -webkit-transform: translateX(0);
            transform: translateX(0) translateY(0);
  }
  30% {
    -webkit-transform: translateX(100px);
            transform: translateX(100px) translateY(100px);
  }
} */
@keyframes slide-right {
  0% {
    /* -webkit-transform: translateX(0); */
            transform: translateX(0) translateY(100);
  }
  20% {
    /* -webkit-transform: translateX(100px); */
            transform: translateX(200px) translateY(-50px);
           
  }
  40%{
    /* -webkit-transform: translateX(100px); */
            transform: translateX(400px) translateY(-100px);
  }
    60%{
    /* -webkit-transform: translateX(100px); */
            transform: translateX(600px) translateY(100px);
  }
    80%{
    /* -webkit-transform: translateX(100px); */
            transform: translateX(720px) translateY(110px);
  }
      100%{
    /* -webkit-transform: translateX(100px); */
            transform: translateX(750px) translateY(-15px);
  }
  


}



.tickets{
    width: 350px;
    height: 150px;
    background:red;
    top:300px;
    position:relative;
}
.slide-right{
  animation: FirstAnim 2s ease-in-out forwards, secondAnim 0.6s ease-in-out forwards, ThirdAnim 0.6s 0.6s ease-in-out forwards, FourAnim 1s 1.2s ease-in-out forwards;
  animation-iteration-count: 1;
  transform-origin: 50% 50%;
  /* -webkit-animation: animationFrames linear 4s;
  -webkit-animation-iteration-count: 1;
  -webkit-transform-origin: 50% 50%;
  -moz-animation: animationFrames linear 4s;
  -moz-animation-iteration-count: 1;
  -moz-transform-origin: 50% 50%;
  -o-animation: animationFrames linear 4s;
  -o-animation-iteration-count: 1;
  -o-transform-origin: 50% 50%;
  -ms-animation: animationFrames linear 4s;
  -ms-animation-iteration-count: 1;
  -ms-transform-origin: 50% 50%; */
}
    @keyframes FirstAnim{
      from {
        right: 0%;
      }
      to {
        right: -80%;
      }
    }
  @keyframes secondAnim{
    from {
      margin-top: 0%;
		}
		to {
     
			margin-top: -10%;
		}
  }
  @keyframes ThirdAnim{
    from {
      margin-top: -10%;
		}
		to {
			margin-top: 10%;
		}
  }
    @keyframes FourAnim{
    from {
      margin-top: 10%;
		}
		to {
			margin-top: -10%;
		}
  }


</style>
    @keyframes FirstAnim { // PLAVNA ANIMACIQ GG
        from {
            right: 0%;
        }
        to {
            right: -110%;
        }
    }
    @keyframes secondAnim {
        from {
            margin-top: 0%;
        }
        to {
            margin-top: -10%;
        }
    }
    @keyframes ThirdAnim {
        from {
            margin-top: -10%;
        }
        to {
            margin-top: 20%;
        }
    }
    @keyframes FourAnim {
        from {
            margin-top: 20%;
        }
        to {
            margin-top: -10%;
        }
    }
        $animDelay:#{$i * 0.03 };
        .anim#{$i} {
            z-index: 10000000;
            // position: absolute;
            animation: FirstAnim 0.7s ease-in forwards, secondAnim 2s 0.7s ease-out forwards, ThirdAnim 1s 2s ease-out forwards;
        }
    }
} 